apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kseer-agent.name" . }}-poc-script
  labels:
    {{- include "kseer-agent.labels" . | nindent 4 }}
data:
  poc.sh: |-
{{ .Files.Get "files/poc.sh" | indent 4 }}
